orders/urls.py
"""Set the url for the views."""

from django.conf import settings
from django.conf.urls.static import static
from django.contrib.auth import views as auth_views
from django.urls import include, path, re_path
from rest_framework.routers import DefaultRouter

from . import views

# API urls generator
router = DefaultRouter()
router.register(r'customer', views.CustomerAPIList)
router.register(r'order', views.OrderAPIList)
router.register(r'item', views.ItemAPIList)
router.register(r'order_item', views.OrderItemAPIList)
router.register(r'invoice', views.InvoiceAPIList)
router.register(r'expense', views.ExpenseAPIList)
router.register(r'expense_category', views.ExpenseCategoryAPIList)
router.register(r'cashflowio', views.CashFlowIOAPIList)
router.register(r'bank_movement', views.BankMovementAPIList)
router.register(r'status_shift', views.StatusShiftAPIList)
router.register(r'timetable', views.TimetableAPIList)

urlpatterns = [
    # The root url
    path('', views.main, name='main'),
    path('search', views.search, name='search'),

    # Populate database
    path('populate', views.populate_trigger, name='populate'),

    # List related urls
    path('kanban', views.kanban, name='kanban'),
    path('customers', views.customerlist, name='customerlist'),
    path('items', views.itemslist, name='itemslist'),
    path('pqueue/manager', views.pqueue_manager, name='pqueue_manager'),
    path('pqueue/tablet',
         views.pqueue_tablet, name='pqueue_tablet'),
    path('invoices', views.invoiceslist, name='invoiceslist'),
    path('stock_manager', views.stock_manager, name='stock_manager'),

    # Object related urls
    re_path(r'^order/view/(?P<pk>[0-9]+)$',
            views.order_view, name='order_view'),
    re_path(r'^order/express/(?P<pk>[0-9]+)$',
            views.order_express_view, name='order_express'),
    re_path(r'^customer_view/(?P<pk>[0-9]+)$',
            views.customer_view, name='customer_view'),

    # Printer view
    re_path(r'^ticket_print&invoice_no=(?P<invoice_no>[0-9]+)$',
            views.printable_ticket, name='ticket_print'),

    # Generic views
    path('timetables/', views.TimetableList.as_view(), name='timetables'),

    # AJAX related urls
    path('actions/', views.Actions.as_view(), name='actions'),
    path('orders-CRUD/', views.OrdersCRUD.as_view(), name='orders-CRUD'),
    path('items-CRUD/', views.ItemsCRUD.as_view(), name='items-CRUD'),
    path('orderitems-CRUD/',
         views.OrderItemsCRUD.as_view(), name='orderitems-CRUD'),
    path('comments-CRUD/', views.CommentsCRUD.as_view(), name='comments-CRUD'),
    path('cashflowio-CRUD/', views.CashFlowIOCRUD.as_view(),
         name='cashflowio-CRUD', ),
    path('changelog/', views.changelog, name='changelog'),
    path('item-selector/', views.item_selector, name='item-selector'),
    path('queue-actions/', views.pqueue_actions, name='queue-actions'),

    # AJAX Hints
    path('customer-hints/', views.customer_hints, name='customer-hints'),
    path('group-hints/', views.group_hints, name='group-hints'),

    # Loging related urls
    path('accounts/login/', auth_views.LoginView.as_view(), name='login'),
    path('accounts/logout/', auth_views.LogoutView.as_view(), name='logout'),
    path('add-hours', views.add_hours, name='add_hours'),

    # The API url
    path('API/', include(router.urls)),

] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

tz/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('orders.urls')),
]

orders/models.py
"""Orders app let manage and control customers, orders and timing.

Its intended use is for business related to tailor made clothes.
"""

import io
from datetime import date, timedelta

from django.contrib.auth.models import User
from django.core.exceptions import ObjectDoesNotExist, ValidationError
from django.db import models
from django.utils import timezone
from django.utils.translation import gettext_lazy as _
from django.template.loader import render_to_string

from . import managers, settings
from .utils import WeekColor, prettify_times
from decouple import config

from todoist.api import TodoistAPI
from reportlab.pdfgen import canvas
from reportlab.lib.units import mm


def default_category():
    """Get or create the default category for expenses."""
    obj, _ = ExpenseCategory.objects.get_or_create(
        name='default', description='The default category')
    return obj.pk


class Customer(models.Model):
    """Hold the data relative to Customers."""

    creation = models.DateTimeField('Alta', default=timezone.now)
    name = models.CharField('Nombre', max_length=64)
    address = models.CharField('Dirección', max_length=64, blank=True)
    city = models.CharField('Localidad', max_length=32, blank=True)
    phone = models.IntegerField('Telefono')
    email = models.EmailField('Email', max_length=64, blank=True)
    CIF = models.CharField('CIF', max_length=20, blank=True)
    cp = models.IntegerField('CP')
    notes = models.TextField('Observaciones', blank=True, null=True)
    provider = models.BooleanField('Proveedor', default=False)
    group = models.BooleanField('Grupo', default=False)

    def __str__(self):
        """Get the name of the entry."""
        return self.name

    def clean(self):
        """Avoid duplicate customers."""
        exists = Customer.objects.filter(name=self.name)
        if exists:
            for customer in exists:
                duplicated = (customer.address == self.address and
                              customer.city == self.city and
                              customer.phone == self.phone and
                              customer.email == self.email and
                              customer.CIF == self.CIF and
                              customer.cp == self.cp and
                              customer.notes == self.notes)
                if duplicated:
                    raise ValidationError({'name': _('The customer already ' +
                                                     'exists in the db')})

        # Avoid being provider & group @ the same time
        if self.provider and self.group:
            raise ValidationError(
                {'provider': _('Un cliente no puede ser proveedor y grupo al' +
                               ' mismo tiempo')})

    def save(self, *args, **kwargs):
        """Override save method."""
        # if clean() was not called, providers are default, this avoids being
        # group and provider simultaneously
        if self.provider:
            self.group = False

        # Capitalize strings for consistency
        charfields = [self.name, self.address, self.city, self.email,
                      self.CIF, self.notes, ]
        uppercased = [f.upper() if f else '' for f in charfields]
        self.name, self.address, self.city = uppercased[:3]
        self.email, self.CIF, self.notes = uppercased[3:]

        # Look for already saved cities and overwrite provided city since zip
        # codes are unique
        valid_cities = Customer.objects.exclude(city__iexact='SERVER')
        c0 = valid_cities.filter(cp=self.cp).exclude(cp=0)
        c0 = c0.exclude(pk=self.pk)  # when having one, it must be editable.
        if c0.exists():
            self.city = c0.first().city

        # If no cp is provided we should find a suitable city already in the db
        if self.cp == 0 and self.city:
            c0 = valid_cities.filter(city__iexact=self.city)
            if c0.exists():
                self.cp = c0.first().cp

        super().save(*args, **kwargs)

    def email_name(self):
        """Get first name in lower case and properly capitalized."""
        return self.name.lower().split()[0].capitalize()

    class Meta:
        ordering = ('name',)


class Order(models.Model):
    """The main object, store the order info."""

    STATUS = (
        # Shop
        ('1', 'Icebox'),
        # WorkShop
        ('2', 'En cola'),
        ('3', 'En proceso'),
        ('4', 'Confección'),  # deprecated since 2020
        ('5', 'Remate'),  # deprecated since 2020
        # Shop
        ('6', 'En espera'),
        ('7', 'Entregado'),
        ('8', 'Cancelado'),
        ('9', 'Facturado')
    )

    PRIORITY = (
        ('1', 'Alta'),
        ('2', 'Normal'),
        ('3', 'Baja')
    )
    inbox_date = models.DateTimeField(default=timezone.now)
    user = models.ForeignKey('auth.User', on_delete=models.CASCADE)
    customer = models.ForeignKey(
        Customer, on_delete=models.CASCADE, null=True,
        related_name='order')
    membership = models.ForeignKey(
        Customer, limit_choices_to={'group': True}, blank=True,
        null=True, on_delete=models.SET_NULL, related_name='group_order')
    ref_name = models.CharField('Referencia', max_length=32)
    delivery = models.DateField('Entrega prevista', blank=True)
    status = models.CharField(max_length=1, choices=STATUS, default='1')
    priority = models.CharField(
        'Prioridad', max_length=1, choices=PRIORITY, default='2')
    confirmed = models.BooleanField('Confirmado', default=True)

    # Measures
    waist = models.DecimalField('Cintura', max_digits=5, decimal_places=2,
                                default=0)
    chest = models.DecimalField('Pecho', max_digits=5, decimal_places=2,
                                default=0)
    hip = models.DecimalField('Cadera', max_digits=5, decimal_places=2,
                              default=0)
    lenght = models.DecimalField('Largo', max_digits=5, decimal_places=2,
                                 default=0)
    others = models.TextField('Observaciones', blank=True, null=True)

    # Pricing
    # budget was deprecated by 2019 on invoices behalf
    # prepaid was deprecated by 2020 on cashflow model behalf
    budget = models.DecimalField(
        'Presupuesto', max_digits=7, decimal_places=2, blank=True, null=True)
    prepaid = models.DecimalField(
        'Prepago', max_digits=7, decimal_places=2, blank=True, null=True,
        default=0)
    discount = models.PositiveSmallIntegerField('Descuento %', default=0)

    # Custom managers
    objects = models.Manager()
    live = managers.LiveOrders()
    outdated = managers.OutdatedOrders()
    obsolete = managers.ObsoleteOrders()

    def __str__(self):
        """Object's representation."""
        return '%s %s %s' % (self.pk,
                             self.customer, self.ref_name)

    def clean(self):
        """Set validation constraints."""
        # Ensure that customer is not provider
        if self.customer and self.customer.provider:
            msg = 'El cliente no puede ser proveedor'
            raise ValidationError({'customer': _(msg)})

        # Ensure that discount does not overrun above 100%
        if self.discount > 100:
            msg = 'El descuento no puede ser superior al 100%'
            raise ValidationError({'discount': _(msg)})

    def save(self, *args, **kwargs):
        """Override save method."""
        # delete all the express orders that are open but not invoiced
        deprecated = Order.objects.filter(
            status='7').filter(ref_name__iexact='quick').exclude(pk=self.pk)
        if deprecated.exists():
            for order in deprecated:
                order.delete()

        # ensure invoiced orders are in status 9
        try:
            self.invoice
        except ObjectDoesNotExist:
            pass
        else:
            self.status = '9'

        # ensure trapuzarrak is always Confirmed
        if self.customer and self.customer.name.lower() == 'trapuzarrak':
            self.confirmed = True

        # ensure membership field is a group customer
        if self.membership and not self.membership.group:
            self.membership = None

        # Since 2020 statuses 4 & 5 are deprecated so redirect them to status 3
        if self.status in ('4', '5'):
            self.status = '3'

        super().save(*args, **kwargs)

        """After saving, add a new StatusShift (will be created only if status
        has changed)"""
        StatusShift.objects.create(order=self, status=self.status)

    def delete(self, *args, **kwargs):
        """Override delete method.

        Ensure stock qtys are returned to the store by deleting individual
        items since CASCADE does not call items.delete()
        """
        for i in self.items.all():
            i.delete()
        super().delete(*args, **kwargs)

    def kill(self, pay_method='C'):
        """Kill the order.

        Kill is the only entry point for invoicing orders. It sets the last
        state an order should have.
        """
        # Avoid killed orders to be rekilled
        try:
            self.invoice
        except ObjectDoesNotExist:
            pass
        else:
            exit

        # If there are pending payments, kill'em
        if self.pending:
            CashFlowIO.objects.create(
                order=self, amount=self.pending, pay_method=pay_method)

        """
        Only shifting up to status 7 with kanban_forward updates the
        delivery date, so update it if we're delayed (like for express orders).
        """
        if self.status != '7':
            self.deliver()  # Creates status shift

        # Set status to 9 (invoiced)
        self.status = '9'
        self.save()  # Also creates status shift and closes it

        # And issue the invoice
        i = Invoice(reference=self, pay_method=pay_method, amount=self.total)
        i.save(kill=True)

tz/orders/views.py
from django.shortcuts import render, redirect
from .models import Comment, Customer, Order, CommentCheck
from django.utils import timezone
from .forms import CustomerForm, OrderForm
from django.contrib.auth.decorators import login_required
from datetime import datetime


# First check is a valid User
@login_required()
def main(request):
    """Create the root view."""
    # Query all active orders
    orders = Order.objects.exclude(status=7).order_by('-inbox_date')

    # Query last commnents on active orders
    comments = Comment.objects.filter(reference__in=orders)
    comments = comments.order_by('-creation')

    cur_user = request.user
    now = datetime.now()

    dict4view = {'orders': orders,
                 'comments': comments,
                 'user': cur_user,
                 'now': now,
                 'title': 'TrapuZarrak · Inicio',
                 'footer': True,
                 }

    return render(request, 'tz/main.html', dict4view)


@login_required()
def new_customer(request):
    """Create new customers with a form view."""
    if request.method == "POST":
        """ When coming from edit view, save the changes (if they are valid)
        and jump to main page
        """
        form = CustomerForm(request.POST)

        if form.is_valid():
            customer = form.save(commit=False)
            customer.creation = timezone.now()
            customer.save()
            return redirect('main')
    else:
        form = CustomerForm()
        now = datetime.now()
        return render(request, 'tz/new_customer.html',
                      {'form': form,
                       'now': now,
                       'title': 'TrapuZarrak · Nuevo Cliente',
                       'footer': False,
                       })


@login_required()
def new_order(request):
    """Create new customers with a form view."""
    if request.method == "POST":
        """ When coming from edit view, save the changes (if they are valid)
        and jump to main page
        """
        form = OrderForm(request.POST)

        if form.is_valid():
            customer = form.save(commit=False)
            customer.creation = timezone.now()
            customer.user = request.user
            customer.save()
            return redirect('main')
    else:
        form = OrderForm()
        now = datetime.now()
        return render(request, 'tz/new_order.html',
                      {'form': form,
                       'now': now,
                       'title': 'TrapuZarrak · Nuevo Pedido',
                       'footer': False,
                       })

orders/templates/includes/custom_forms/add_times.html
{% comment %}
Add/Edit times for order items.

This custom form template lets create or edit times for order items in pqueue tablet view.
{% endcomment %}
{% load widget_tweaks %}

<div class="row js-set-times">
  <div class="col">
    <div class="form-group">
      {{form.crop.label_tag}}
      {% render_field form.crop class="form-control" %}
    </div>
  </div>
  <div class="col">
    <div class="form-group">
      {{form.sewing.label_tag}}
      {% render_field form.sewing class="form-control" %}
    </div>
  </div>
  <div class="col">
    <div class="form-group">
      {{form.iron.label_tag}}
      {% render_field form.iron class="form-control" %}
    </div>
  </div>
</div>

orders/templates/includes/custom_forms/customer.html
{% comment %}Add/Edit customers. Depends on regular form include.{% endcomment %}

{% load widget_tweaks %}
<div class="form-group">
  {{ form.name.label_tag }}
  {% if form.name.field.required%}<span class="text-danger">*</span>{%endif%}
  {% render_field form.name class="form-control" %}
</div>
<div class="row">
  <div class="col-8">
    <div class="form-group">
      {{ form.address.label_tag }}
      {% if form.address.field.required%}<span class="text-danger">*</span>{%endif%}
      {% render_field form.address class="form-control" %}
    </div>
  </div>
  <div class="col-4">
    <div class="form-group">
      {{ form.city.label_tag }}
      {% if form.city.field.required%}<span class="text-danger">*</span>{%endif%}
      {% render_field form.city class="form-control" %}
    </div>
  </div>
</div>
<div class="form-group">
  {{ form.email.label_tag }}
  {% if form.email.field.required%}<span class="text-danger">*</span>{%endif%}
  {% render_field form.email class="form-control" %}
</div>
<div class="row">
  <div class="col-5">
    <div class="form-group">
      {{ form.phone.label_tag }}
      {% if form.phone.field.required%}<span class="text-danger">*</span>{%endif%}
      {% render_field form.phone class="form-control" %}
    </div>
  </div>
  <div class="col-4">
    <div class="form-group">
      {{ form.CIF.label_tag }}
      {% if form.CIF.field.required%}<span class="text-danger">*</span>{%endif%}
      {% render_field form.CIF class="form-control" %}
    </div>
  </div>
  <div class="col-3">
    <div class="form-group">
      {{ form.cp.label_tag }}
      {% if form.cp.field.required%}<span class="text-danger">*</span>{%endif%}
      {% render_field form.cp class="form-control" %}
    </div>
  </div>
</div>
<div class="form-group">
  {{ form.notes.label_tag }}
  {% if form.notes.field.required%}<span class="text-danger">*</span>{%endif%}
  {% render_field form.notes class="form-control" %}
</div>
<small>*El cp se añade automáticamente al añadir la ciudad y viceversa. (Solo si ya están registrados en la base de datos)</small>

orders/templates/includes/custom_forms/edit_stock.html
{% comment %}
The stock edit form.

Renders this form in the selected item on stock tabs to perform an edit on the stock.
{% endcomment %}

{% load widget_tweaks %}
<div class="modal-header">
  <h4 class="modal-title">{{modal_title}}</h4>
  <a type="button" class="close" data-dismiss="modal" aria-label="Close">
    <span aria-hidden="true"><i class="fa fa-times"></i></span>
  </a>
</div>

<form class="js-crud-form" method="post" action="{% url 'items-CRUD' %}">
  {% csrf_token %}
  <input type="hidden" name="action" value="edit-stock">
  <input type="hidden" name="item_pk" value="{{item.pk}}">
  {% render_field form.name.as_hidden %}
  {% render_field form.item_type.as_hidden %}
  {% render_field form.item_class.as_hidden %}
  {% render_field form.size.as_hidden %}
  {% render_field form.fabrics.as_hidden %}
  {% render_field form.price.as_hidden %}
  {% render_field form.foreing.as_hidden %}
  <div class="modal-body">
    <div class="row">
      <div class="col-9 d-flex my-1">
        {{item.html_string}}
      </div>
      <div class="col-3">
        <div class="form-group">
          {% render_field form.stocked class="form-control" %}
        </div>
      </div>
    </div>
  </div>
  <div class="modal-footer">
    <div class="mr-auto d-none" id="check-success">
      <i class="far fa-check text-success"></i> Guardado, puedes cerrar esta ventana.
    </div>
    <div class="mr-auto d-none" id="bg-working">
      <i class="far fa-spinner fa-spin"></i> Procesando, ten paciencia.
    </div>
    <div class="mr-auto">
      {{form.errors}}
    </div>
    <button type="submit" class="btn btn-outline-success js-submit">
      <i class="fas fa-check mr-1"></i>Guardar
    </button>
  </div>
</form>

orders/templates/includes/custom_forms/object_item.html
{% comment %}
Add/Edit base items. Depends on regular form template.
{% endcomment %}

{% load widget_tweaks %}
<div class="form-group">
  {{form.name.label_tag}}
  {% render_field form.name class="form-control" %}
</div>
<div class="row">
  <div class="col-5">
    <div class="form-group">
      {{form.item_type.label_tag}}
      {% render_field form.item_type class="form-control" %}
    </div>
  </div>
  <div class="col-5">
    <div class="form-group">
      {{form.item_class.label_tag}}
      {% render_field form.item_class class="form-control" %}
    </div>
  </div>
  <div class="col-2">
    <div class="form-group">
      {{form.size.label_tag}}
      {% render_field form.size class="form-control" %}
    </div>
  </div>
</div>
<div class="row">
  <div class="col">
    <div class="form-group">
      {{form.fabrics.label_tag}}
      {% render_field form.fabrics class="form-control" %}
    </div>
  </div>
  <div class="col">
    <div class="form-group">
      {{form.price.label_tag}}
      {% render_field form.price class="form-control" %}
    </div>
  </div>
  <div class="col">
    <div class="form-group">
      {{form.stocked.label_tag}}
      {% render_field form.stocked class="form-control" %}
    </div>
  </div>
</div>
<div class="form-group">
  {{form.notes.label_tag}}
  {% render_field form.notes class="form-control" %}
</div>
<input type="hidden" name="foreing" value="{{form.foreing.value}}">

orders/templates/includes/custom_forms/order.html
{% comment %}
Add/Edit orders.

This custom form template lets create or edit orders. Does not depend on regular form template.
{% endcomment %}


{% load widget_tweaks %}

<div class="modal-header">
  <h4 class="modal-title">{{modal_title}}</h4>
  <a type="button" class="close" data-dismiss="modal" aria-label="Close">
    <span aria-hidden="true"><i class="fa fa-times"></i></span>
  </a>
</div>
<form class="js-crud-form" method="post" action="{% url 'orders-CRUD' %}">
  {% csrf_token %}
  <input type="hidden" name="action" value="main">
  <input type="hidden" name="user" value="{{user.pk}}">
  {% render_field form.inbox_date.as_hidden %}
  {% render_field form.status.as_hidden %}
  {% if order %}<input type="hidden" name="pk" value="{{order.pk}}">{% endif %}

  <div class="modal-body">

    {# Customer & group row #}
    <div class="row">
      <div class="col">
        <div class="form-group">
          {{ form.customer.label_tag }}
          {% if order.customer %}
            <input class="form-control js-hints" type="text" value="{{order.customer.name}}" id="customer-hints" autocomplete="off">
            <input type="hidden" name="customer" value="{{order.customer.pk}}" id="selected-customer">
          {% else %}
            <input class="form-control js-hints" type="text" placeholder="Empieza a escribir..." id="customer-hints" autocomplete="off">
            <input type="hidden" name="customer" value="" id="selected-customer">
          {% endif %}
          <div class="d-flex flex-column" id="search-result-customer"></div>
        </div>
      </div>
      <div class="col">
        <div class="form-group">
          <label for="id_membership">Grupo:</label>
          {% if order.group %}
            <input class="form-control js-hints" type="text" value="{{order.group.name}}" id="group-hints" autocomplete="off">
            <input type="hidden" name="membership" value="{{order.group.pk}}" id="selected-group">
          {% else %}
            <input class="form-control js-hints" type="text" placeholder="Empieza a escribir..." id="group-hints" autocomplete="off">
            <input type="hidden" name="membership" value="" id="selected-group">
          {% endif %}
          <div class="d-flex flex-column" id="search-result-group"></div>
        </div>
      </div>
    </div>
    <div class="form-group">
      {{ form.ref_name.label_tag }}
      {% render_field form.ref_name class="form-control" %}
    </div>
    <div class="row">
      <div class="col">
        <div class="form-group">
          {{ form.delivery.label_tag }}
          <input type="date" class="form-control" name="{{ form.delivery.name }}" id="{{ form.delivery.id_for_label }}" {% if form.delivery.value != None %} value="{{ form.delivery.value|stringformat:'s' }}" {% endif %}>
        </div>
      </div>
      <div class="col">
        <div class="form-group">
          {{ form.priority.label_tag }}
          {% render_field form.priority class="form-control" %}
        </div>
      </div>
      <div class="col-3">
        <div class="form-group">
          {{ form.discount.label_tag }}
          {% render_field form.discount class="form-control" %}
        </div>

      </div>
    </div>
    <div class="form-group">
      <div class="row">
        <div class="col">
          {{ form.waist.label_tag }}
          {% render_field form.waist class="form-control" %}
        </div>
        <div class="col">
          {{ form.chest.label_tag }}
          {% render_field form.chest class="form-control" %}
        </div>
        <div class="col">
          {{ form.hip.label_tag }}
          {% render_field form.hip class="form-control" %}
        </div>

        <div class="col">
          {{ form.lenght.label_tag }}
          {% render_field form.lenght class="form-control" %}
        </div>
      </div>
    </div>

    {# Description field collapse #}
    <div class="d-flex flex-column">
      <div class="collapse" id="add-description">
        {% render_field form.others class="form-control" rows="3"%}
      </div>
      <h5 style="cursor:pointer" data-toggle="collapse" data-target="#add-description" aria-hidden="true" aria-expanded="true">Descripción<i class="far fa-plus-circle ml-2 js-plusToCaret"></i></h5>
    </div>
    <div class="form-check">
      {% render_field form.confirmed class="form-check-input" %}
      <label for="id_confirmed" class="form-check-label"> Pedido Confirmado</label>
    </div>
  </div>

  {# Footer #}
  <div class="modal-footer">
    <div class="mr-auto d-none" id="check-success">
      <i class="far fa-check text-success"></i> Guardado, puedes cerrar esta ventana.
    </div>
    <div class="mr-auto d-none" id="bg-working">
      <i class="far fa-spinner fa-spin"></i> Procesando, ten paciencia.
    </div>
    <div class="mr-auto">
      {{form.errors}}
    </div>
    <button type="submit" class="btn btn-outline-success js-submit">
      <i class="fas fa-check mr-1"></i>Guardar
    </button>
  </div>

</form>

orders/templates/includes/custom_forms/order_express.html
{# Create a new order express #}

{% load widget_tweaks %}
<div class="d-flex">
  <div class="form-group">
    <label for="cp_id">Codigo postal</label>
    <input type="number" class="form-control" name="cp" value="0" id="cp_id" maxlength="5" step="1">
    <small>Puedes dejarlo en 0 si no lo sabes aún.</small>
  </div>
</div>